Invoke protobuf_deps() from protobuf dependency
This function defines the `@rules_jvm_external` repository, which is needed now.

This fixes the folowing error in `update-deps.sh`:

```
ERROR: /tmp/tmp.jWq8sT30YZ/external/com_google_protobuf/BUILD:814:6: error loading package '@com_google_protobuf//java/core': Unable to find package for @rules_jvm_external//:defs.bzl: The repository '@rules_jvm_external' could not be resolved. and referenced by '@com_google_protobuf//:java_toolchain'
```