OSSM-3429: Fix a compiler error
Recently CI saw errors like this:
```
bazel-out/k8-fastbuild/bin/external/org_llvm_releases_compiler_rt/_virtual_includes/fuzzed_data_provider/fuzzer/FuzzedDataProvider.h:194:38: error: no member named 'numeric_limits' in namespace 'std'
  return ConsumeIntegralInRange(std::numeric_limits<T>::min(),
                                ~~~~~^
```

Apparently this is due to a incompatibility between the `compiler-rt`
dependency and the clang version we use (14.0).

This is fixed by updating `compiler-rt` to match clang 14. Actually This commit
cherry-picks the relevant changes done in upstream a while ago: https://github.com/envoyproxy/envoy/pull/21135