Add protobuf_version.bzl to the protobuf dependency
It's not present in the 3.18.0 protobuf tarball, and it's now required.

This fixes the folowing error in `update-deps.sh`:

```
ERROR: /tmp/tmp.jWq8sT30YZ/external/com_google_protobuf/BUILD:814:6: error loading package '@com_google_protobuf//java/core': cannot load '@com_google_protobuf//:protobuf_version.bzl': no such file and referenced by '@com_google_protobuf//:java_toolchain'
```